#!/usr/bin/env python3
"""Regenerates Sources/ClankerCore/Spend/BundledPrices.swift from LiteLLM's public price table:
the built-in prices the app uses until (or when it can't) download fresh ones.
Keeps Anthropic and OpenAI models. Run before a release (scripts/release.sh does)."""
import json, os, sys, urllib.request

URL = "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "Sources", "ClankerCore", "Spend", "BundledPrices.swift")

with urllib.request.urlopen(URL, timeout=30) as r:
    table = json.load(r)

models = {}
for key, e in table.items():
    if not isinstance(e, dict) or e.get("litellm_provider") not in ("anthropic", "openai"):
        continue
    if "input_cost_per_token" not in e or "output_cost_per_token" not in e:
        continue
    price = {"input": e["input_cost_per_token"], "output": e["output_cost_per_token"]}
    for field, source in (("cacheWrite5m", "cache_creation_input_token_cost"),
                          ("cacheWrite1h", "cache_creation_input_token_cost_above_1hr"),
                          ("cacheRead", "cache_read_input_token_cost")):
        if e.get(source) is not None:
            price[field] = e[source]
    thresholds = [int(k[len("input_cost_per_token_above_"):-len("k_tokens")]) for k in e
                  if k.startswith("input_cost_per_token_above_") and k.endswith("k_tokens")]
    if thresholds:
        tier = f"_above_{min(thresholds)}k_tokens"
        price["longContextFrom"] = min(thresholds) * 1000
        for field, source in (("longInput", "input_cost_per_token"), ("longOutput", "output_cost_per_token"),
                              ("longCacheWrite5m", "cache_creation_input_token_cost"),
                              ("longCacheRead", "cache_read_input_token_cost")):
            if e.get(source + tier) is not None:
                price[field] = e[source + tier]
    models[key.split("/")[-1].lower()] = price

body = json.dumps(dict(sorted(models.items())), separators=(",", ":"))
with open(OUT, "w") as f:
    f.write("// Generated by scripts/update-prices.py from LiteLLM's model price table. Don't edit by hand.\n")
    f.write("enum BundledPrices {\n")
    f.write('    static let json = #"""\n' + body + '\n"""#\n')
    f.write("}\n")
print(f"{len(models)} models → {os.path.relpath(OUT)}", file=sys.stderr)
